[package]
name = "wallet-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "1.1.0"
hdpath = "0.6.3"
rand = "0.8.5"
bip32 = "0.4.0"
secp256k1 = "0.25.0"
hex = "0.4"
sha2 = "0.10"
ripemd = "0.1.3"
bech32 = "0.9"
hdkey = "0.0.5"
